/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x97, 0xD0, 0xA5, 0x97, 0x57, 0x48, 0xD0, 0x4F}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 16
#define DYNAMIC_KEYMAP_MACRO_COUNT 64
#define VIAL_COMBO_ENTRIES DYNAMIC_KEYMAP_MACRO_COUNT

#define COMBO_ONLY_FROM_LAYER 0

#define TAP_CODE_DELAY 5
#define SS_TAP_CODE_DELAY SS_DELAY(TAP_CODE_DELAY)
#define STRING_DELAY_INTERVAL TAP_CODE_DELAY
