/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x97, 0xD0, 0xA5, 0x97, 0x57, 0x48, 0xD0, 0x4F}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 20
#define DYNAMIC_KEYMAP_MACRO_COUNT 64
#define VIAL_COMBO_ENTRIES DYNAMIC_KEYMAP_MACRO_COUNT

#define COMBO_ONLY_FROM_LAYER 0

#define TAP_CODE_DELAY 5
#define SS_TAP_CODE_DELAY SS_DELAY(TAP_CODE_DELAY)
#define STRING_DELAY_INTERVAL TAP_CODE_DELAY

#ifndef PERMISSIVE_HOLD_PER_KEY
  #define PERMISSIVE_HOLD_PER_KEY
#endif

#ifndef HOLD_ON_OTHER_KEY_PRESS_PER_KEY
  #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#endif

#define EE_HANDS

// Mouse
#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define MOUSEKEY_DELAY 0

#define MK_C_OFFSET_UNMOD 12
#define MK_C_INTERVAL_UNMOD 16

#define MK_C_OFFSET_0 4
#define MK_C_INTERVAL_0 16

#define MK_C_OFFSET_1 24
#define MK_C_INTERVAL_1 16

#define MK_C_OFFSET_2 32
#define MK_C_INTERVAL_2 16
// End Mouse
